# Generated by Django 4.0.3 on 2023-04-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_userdetails_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Checkbox',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
